# Generated by Django 3.1.4 on 2020-12-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201203_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='questions.Category'),
        ),
        migrations.DeleteModel(
            name='Qcategory',
        ),
    ]
