# Generated by Django 3.1.4 on 2020-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default='content', max_length=1000),
            preserve_default=False,
        ),
    ]
