# Generated by Django 3.1.4 on 2020-12-17 10:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20201216_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='محتوا'),
        ),
    ]
