# Generated by Django 3.1.4 on 2020-12-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20201221_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
    ]
