# Generated by Django 3.1.4 on 2020-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20201228_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='questions.Tag', verbose_name='تگ ها'),
        ),
    ]
