# Generated by Django 3.1.4 on 2021-01-03 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0018_auto_20201229_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_created'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوال ها'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='question_likes', to=settings.AUTH_USER_MODEL, verbose_name='رای  ها'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
